#!/bin/bash

# Function to check if a user is an admin
is_admin() {
    grep -q "^$USER$" admins.txt
    return $?
}

# Function to list all databases that the user has access to
list_databases() {
    database_path="Databases"

    # Check if the 'Databases' directory exists
    if [ -d "$database_path" ]; then
        # Check if there are any databases
        if [ -n "$(ls -A "$database_path")" ]; then
            echo "Available databases:"
            for db in "$database_path"/*; do
                if [ -d "$db" ]; then
                    db_name=$(basename "$db")

                    # Check if the user has permission to access the database
                    if [ -r "$db" ] || [ -x "$db" ] || [ "$(id -Gn | grep -wq 'admins.txt')" ]; then
                        echo "$db_name"
                    fi
                fi
            done
        else
            echo "No databases found."
        fi
    else
        echo "No databases found."
    fi
}
# Function to list all tables in a database
list_tables() {
    database_name=$1
    table_path="Databases/$database_name"

    # Check if the database exists
    if [ -d "$table_path" ]; then
        # Check if there are any tables in the database
        if [ -n "$(ls -A "$table_path")" ]; then
            echo "Tables in database '$database_name':"
            ls "$table_path" | sed 's/\.txt$//'
        else
            echo "No tables found in database '$database_name'."
            exit 1
        fi
    else
        echo "Database '$database_name' does not exist."
    fi
}

# Function to insert data into a table
insert_data() {
    database_name=$1
    table_name=$2
    
    # Get the owner of the database folder
    folder_owner=$(stat -c '%U' "Databases/$database_name")
    # Get the current user
    current_user=$(id -un)
    
    # Check if the database exists
    if [ -d "Databases/$database_name" ]; then
        # Check if the user is an admin or the owner of the database
        if is_admin || [ "$folder_owner" = "$current_user" ]; then
            # Check if the table exists
            if [ -f "Databases/$database_name/$table_name.txt" ]; then
                table_path="Databases/$database_name/$table_name.txt"

                # Get the column names from the first line of the table file
                column_names=$(head -n 1 "$table_path")

                # Read the data for each column except the first column (ID)
                declare -a data_value
                
                # Get the last ID from the table file
                last_id=$(tail -n 1 "$table_path" | cut -d',' -f1)
                new_id=$((last_id + 1))
                echo "new row with id: $new_id"
                data_values+=("$new_id")
                
                # loop through the rest of the columns
                for column in $(echo "$column_names" | cut -d',' -f2-); do
                    if [ "$column" = "ID" ]; then 
                    	echo "if"
                        continue
                    fi
                    echo "column: $column"
                    read -p "Enter the value for column '$column': " value
                    data_values+=("$value")
                done

                # Append the new data to the table file
                echo "$(IFS=','; echo "${data_values[*]}")" >>"$table_path"

                echo "Data inserted successfully into table '$table_name' in database '$database_name'."    
                # add log
               /bin/bash "./create_log" "insert_data" "$database_name" "$USER"
            else
                echo "Table '$table_name' does not exist in database '$database_name'."
                exit 1
            fi
        else
            echo "You do not have permission to insert data into the database '$database_name'."
            exit 1
        fi
    else
        echo "Database '$database_name' does not exist."
        exit 1
    fi
}


# Check if the 'Databases' directory exists
if [ ! -d "Databases" ]; then
    echo "No databases found."
    exit 1
fi

# List all databases that the user has access to
echo "Listing all databases you have access to:"
list_databases

# Read the database name from user input
read -p "Enter the name of the database to insert data into: " database_name

# Check if the database name is empty
if [ -z "$database_name" ]; then
    echo "Database name cannot be empty."
    exit 1
fi

# Check if the database exists
if [ ! -d "Databases/$database_name" ]; then
    echo "Database '$database_name' does not exist or you do not have access to it."
    exit 1
fi

# List all tables in the selected database
echo "Listing all tables in database '$database_name':"
list_tables "$database_name"

# Read the table name from user input
read -p "Enter the name of the table to insert data into: " table_name

# Check if the table name is empty
if [ -z "$table_name" ]; then
    echo "Table name cannot be empty."
    exit 1
fi
# Insert data into the table
insert_data "$database_name" "$table_name"
