#!/bin/bash

operation=""

while [ "$operation" != "0" ]; 
do 
	read -p "Welcome $USER to our Database Mangement 
 	choose what you want to do here 
 	Enter 1 to create a database 
 	Enter 2 to delete a database
 	Enter 3 to empty a database
 	Enter 4 to create a table in database
 	Enter 5 to delete a table in database
 	Enter 6 to insert data into a table in database
 	Enter 7 to retrieve data from a table in database
 	Enter 8 to update data from a table in database
 	Enter 9 to delete data from a table in database
 	Enter 10 to create backup for a database 
 	Enter 11 to restore a backup for a database
 	Enter 12 to export log files to excel files
 	Enter 13 to retrieve logs
 	Enter 0 to Exit:" operation
	echo $operation
	case "$operation" in
          	 1)
                	/bin/bash "./create_database"
                	;;
            	2)
                	/bin/bash "./delete_database"
                	;;
            	3)
            		/bin/bash "./empty_database"
            		;;
            	4) 
            		/bin/bash  "./create_table"
            		;;
            	5)
            		/bin/bash "./delete_table"
            		;;
            	6)
            		/bin/bash "./insert_data"
            		;;
            	7)
            		/bin/bash "./retrieve_data"
            		;;
            	8)
            		/bin/bash "./update_data"
            		;;
            	9)	
            		/bin/bash "./delete_data"
            		;;
            	10)
            	        /bin/bash "./create_backup"
            		;;  
            	11)
            	        /bin/bash "./restore_backup"
            		;;
            	12)
            	        /bin/bash "./export_logs"
            		;; 	
            	13)
            	        /bin/bash "./retrieve_logs"
            		;; 		
            	0)
            		echo "Thank u $USER for using our Database Mangement"
            		;;					    
            	*)
            	    echo "Invalid option selected."
            	    ;;
       	 esac
done
