#!/bin/bash

# Function to check if a user is an admin
is_admin() {
    grep -q "^$USER$" admins.txt
    return $?
}

# Function to list all databases that the user has access to
list_databases() {
    database_path="Databases"

    # Check if the 'Databases' directory exists
    if [ -d "$database_path" ]; then
        # Check if there are any databases
        if [ -n "$(ls -A "$database_path")" ]; then
            echo "Available databases:"
            for db in "$database_path"/*; do
                if [ -d "$db" ]; then
                    db_name=$(basename "$db")
                    # Check if the user is an admin or the owner of the database
                    if is_admin  [ "$USER" = "$db_name" ]; then
                        echo "$db_name"
                    fi
                fi
            done
        else
            echo "No databases found."
            exit 1
        fi
    else
        echo "No databases found."
        exit 1
    fi
}

# Function to retrieve all table data
retrieve_all_data() {
    database_name=$1
    table_name=$2

    # Check if the table exists
    if [ -f "Databases/$database_name/$table_name.txt" ]; then
        echo "Retrieving all data from table '$table_name' in database '$database_name':"
        cat "Databases/$database_name/$table_name.txt"
        # add log
       /bin/bash "./create_log" "retrieve_data" "$database_name" "$USER"
    else
        echo "Table '$table_name' does not exist in database '$database_name'."
        exit 1 
    fi
}

# Function to retrieve data based on specific criteria
retrieve_data_by_criteria() {
    database_name=$1
    table_name=$2

    # Check if the table exists
    if [ -f "Databases/$database_name/$table_name.txt" ]; then
        read -p "Enter the value to search for: " search_value
        echo "Retrieving data from table '$table_name' in database '$database_name' based on the criteria '$search_value':"
        grep "$search_value" "Databases/$database_name/$table_name.txt"
        # add log
       /bin/bash "./create_log" "retrieve_data" "$database_name" "$USER"
    else
        echo "Table '$table_name' does not exist in database '$database_name'."
        exit 1
    fi
}
# Fuction to make the user choose which way to retive the data 
choose_way(){
database_name=$1
# Check if the database exists
if [ -d "Databases/$database_name" ]; then
        echo "Retrieving data from private database '$database_name'..."
        echo "Available tables:"
        ls "Databases/$database_name" | sed 's/\.txt$//'
        
        read -p "Enter the table name: " table_name

        echo -n "Choose an option:
       	1. Retrieve all table data
        2. Retrieve data based on specific criteria"
       read -p "Enter your choice: " option

        case "$option" in
            1)
                retrieve_all_data "$database_name" "$table_name"
                ;;
            2)
                retrieve_data_by_criteria "$database_name" "$table_name"
                ;;
            *)
                echo "Invalid option selected."
                ;;
        esac
   
else
    echo "Database '$database_name' does not exist."
    exit 1
fi
}
# List all databases that the user has access to
echo "Listing all databases you have access to:"
list_databases
read -p "Enter the database name: " database_name
choose_way $database_name
