#!/bin/bash

backup_type="$1" # Daily, Weekly, Monthly, Date Specific.
selected_database="$2"  # Database name
max_size=500  # Maximum backup size in megabytes

# Check if the directory exists
if [ ! -d "/opt/Backups/$backup_type" ]; then
    echo "Error: Backup directory '/opt/Backups/$backup_type' not found."
    exit 1
fi

# Check if the database directory exists
if [ ! -d "/opt/Backups/$backup_type/$selected_database" ]; then
    echo "Error: Database directory '/opt/Backups/$backup_type/$selected_database' not found."
    exit 1
fi

# Change to the backup directory
cd "$backup_dir/$selected_database" || exit

# Calculate the total size of the backup directory in megabytes
total_size=$(du -smc . | grep -o -E '^[0-9]+')

# Loop until the total size is below the maximum size
while [ "$total_size" -gt "$max_size" ]; do
    # Find the oldest backup file and remove it
    oldest_file=$(ls -t | tail -n 1)
    rm -f "$oldest_file"

    # Update the total size
    total_size=$(du -smc . | grep -o -E '^[0-9]+')
done

echo "Rotation based on database size completed successfully"

