#!/bin/bash

selected_database=$1  # First argument is the selected database
compression_mode=$2   # Second argument is the compression mode

backup_dir="/opt/Backups/Daily"
database_dir="Databases"

# Check if the directory exists, create it if not
if [ ! -d "$backup_dir" ]; then
    mkdir "$backup_dir"
fi

# Check if the database directory exists
if [ ! -d "$database_dir/$selected_database" ]; then
    echo "Error: Database directory '$database_dir/$selected_database' not found."
    exit 1
fi

# Schedule daily backup at 2:00 AM
(crontab -l ; echo "0 2 * * * /path/to/backup_daily.sh $selected_database $compression_mode") | crontab -

# Get the current date for naming the backup
current_date=$(date +\%Y\%m\%d)

case "$compression_mode" in
    zip)
        # Implement zip compression logic for daily backup
        zip -r "$backup_dir/daily_backup_${selected_database}_$current_date.zip" "$database_dir/$selected_database"
        echo "Daily backup for $selected_database completed successfully"
        ;;
    tar)
        # Implement tar compression logic for daily backup
        tar cf "$backup_dir/daily_backup_${selected_database}_$current_date.tar" -C "$database_dir" "$selected_database"
        echo "Daily backup for $selected_database completed successfully"
        ;;
    gzip)
        # Implement gzip compression logic for daily backup
        tar czf "$backup_dir/daily_backup_${selected_database}_$current_date.tar.gz" -C "$database_dir" "$selected_database"
        echo "Daily backup for $selected_database completed successfully"
        ;;
    *)
        echo "Invalid compression mode selected."
        exit 1
        ;;
esac
database_name="daily_backup_${selected_database}_$current_date"

# Call rotation script based on backup date : 
/bin/bash "./rotate_backups_by_date" "Daily" "$database_name" 

# Call rotation script based on backup size : 
/bin/bash "./rotate_backups_by_size" "Daily" "$database_name"
